### ISSUE TITLE
Diff no longer works on Node 7

### ISSUE THREAD

**Issue by Krinkle** [pihvi/assert-diff#2]
Running `node test/example-internals.js` as example.

**Node 4**
<https://travis-ci.org/Krinkle/assert-diff/jobs/209988947>
<img width="644" alt="screen shot" src="https://cloud.githubusercontent.com/assets/156867/23820879/98649fca-05d7-11e7-80e2-6883301da96d.png">

**Node 6**
<https://travis-ci.org/Krinkle/assert-diff/jobs/209990431>
<img width="612" alt="screen shot 2017-03-10 at 21 36 34" src="https://cloud.githubusercontent.com/assets/156867/23820944/a15cc448-05d9-11e7-9ecb-cdd323fa9574.png">

**Node 7**
<https://travis-ci.org/Krinkle/assert-diff/jobs/209988948>
<img width="800" alt="screen shot" src="https://cloud.githubusercontent.com/assets/156867/23820878/9864209a-05d7-11e7-91c3-0a009acd27d2.png">

When calling `e.toString()` manually it still behaves the same. So it looks like something changed specifically to the way an uncaught error is printed for command-line scripts.

**Comment by Krinkle** [comment]
May be related: https://github.com/nodejs/node/commit/e2f47f5698. If that's the problem then the cause is most likely the fact that the message gets embedded into `e.stack` before assert-diff is able to override it.

**Comment by pihvi** [comment]
Thanks! I'll try to get the fix in and released today.

**Comment by pihvi** [comment]
Fixed in version 1.2.0

Node docs say here https://nodejs.org/api/errors.html#errors_error_message

> The message passed to the constructor will also appear in the first line of the stack trace of the Error, however changing this property after the Error object is created may not change the first line of the stack trace (for example, when error.stack is read before this property is changed).

I guess the "may not change" part came to effect as putting the message to the constructor fixed this.
